<?php 
include 'layout/header.phtml'; 
?>
  <div class="error-container container mt-4">
    <h1 class="error-title">404</h1>
    <p class="error-message">¡Oops! Página no encontrada</p>
    <p class="error-description">Parece que la página que estás buscando no existe, o ha sido movida.</p>
    <a href="<?= BASE_URL ?>" class="btn btn-primary btn-lg">Volver al Inicio</a>
  </div>

  <?php
 include 'layout/footer.phtml';
 


