<?php include 'templates/layout/header.phtml'; ?>
<div class="container mt-4">
    <h2><?= $autor?'Editar autor': 'Agregar autor' ?> </h2>
    <?php if($error){
        require 'error.phtml';
    }
    elseif($mensaje){
        require 'mensaje.phtml';
    }
    ?>
    <form action="<?= BASE_URL . $accion ?>" method="POST" enctype="multipart/form-data">
        
        <?php if ($autor): ?>
            <input type="hidden" name="id_autor" value="<?= $autor->id_autor ?>">
        <?php endif; ?>

        <div class="form-group">
            <label for="nombre_autor">Nombre del Autor</label>
            <input type="text" class="form-control" id="nombre_autor" name="nombre_autor" value="<?= $autor->nombre_autor ?? '' ?>" required>
        </div>

        <div class="form-group">
            <label for="nacionalidad">Nacionalidad</label>
            <input type="text" class="form-control" id="nacionalidad" name="nacionalidad" value="<?= $autor->nacionalidad_autor ?? '' ?>">
        </div>
        <div class="form-group">
            <label for="archivo_foto">Foto</label>
            <input type="file" class="form-control" id="archivo_foto" name="archivo_foto" accept="image/*">
        </div>
        <button type="submit" class="btn btn-success mt-2">Guardar</button>
        
    </form>
</div>
<?php include 'templates/layout/footer.phtml'; ?>