<?php include 'templates/layout/header.phtml'; ?>
<div class="container mt-4">
    <h2>Login</h2>
    <?php if($error){
        require 'error.phtml';
    }
    ?>
    <form action="<?= BASE_URL?>login" method="POST">
        
        <div class="form-group">
            <label for="nombre_usuario">Nombre usuario</label>
            <input type="text" class="form-control" id="nombre_usuario" name="nombre_usuario" required>
        </div>

        <div class="form-group">
            <label for="clave_usuario">Contraseña</label>
            <input type="password" class="form-control" id="clave_usuario" name="clave_usuario" required>
        </div>
            
        <button type="submit" class="btn btn-success mt-2">Login</button>
        
    </form>
</div>
<?php include 'templates/layout/footer.phtml'; ?>