<footer class="bg-light text-dark p-3 mt-5">
  <div class="container">
    <p class="mb-1">&copy; 2024 Biblioteca. Todos los derechos reservados.</p>
    <p><a href="mailto:contacto@biblioteca.com" class="text-dark">Contáctanos</a></p>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

  
