<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>TPE-ESPECIAL</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="styles/app.css" rel="stylesheet">
</head>

<body>


  <header class="bg-dark text-white p-3">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href=<?= BASE_URL ?>>Biblioteca</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
           
            <li class="nav-item">
              <a class="nav-link" href="<?= BASE_URL . 'autores' ?>">Autores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<?= BASE_URL . 'libros' ?>">Libros</a>
            </li>
          </ul>
        </div>
        <div class="col-md-3 text-end">
          <?php
           if(empty($this->usuario)):
           ?>
          <a href="<?= BASE_URL . 'login'?>" class="btn btn-outline-primary me-2">Login</a>
          <?php else: ?>
            <strong>Hola! <?= $this->usuario->nombre_usuario ?> </strong>
            <a href="<?= BASE_URL . 'logout'?>" class="btn btn-outline-primary me-2">Logout</a>
          <?php endif?>
          </div>
          
      </nav>
      <h1 class="mt-3">Sistema de Gestión de la Biblioteca</h1>
    </div>
  </header>